version: 2

jobs:

  publishPackage:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Publish package
          command: |
            cd gatsby-theme-w3f
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            yarn
            yarn publish --access public

workflows:
  version: 2
  test-deploy:
    jobs:
      - publishPackage:
          filters:
            branches:
              only: circleci
